shadow = true  # shadows around stacked views
borders = "outset"  # "simple", "none", or "outset"

[colors]
    background = "#000"
    shadow     = ["#000", "black"]
    view       = "#111"

    primary   = ["#FFF"]
    secondary = "#EEE"
    tertiary  = "#444"

    title_primary   = "cyan"
    title_secondary = "#ffff55"

    highlight          = "cyan"
    highlight_text     = "#000"
    highlight_inactive = "#F55"